import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TrpcProvider from "@/lib/trpc/Provider";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth";
import SessionProvider from "@/lib/auth/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en" className="light">
      <body className={cn("font-sans antialiased grainy", inter.className)}>
        <SessionProvider session={session} refetchInterval={5 * 60}>
          <TrpcProvider>
            <Navbar />
            {children}
            <Toaster />
          </TrpcProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
